# Generated by Django 5.0.6 on 2024-06-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name='Are you a Developer?Went to get Job?'),
        ),
    ]
