# Generated by Django 5.0.6 on 2024-06-07 12:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HireNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring', models.CharField(choices=[('oneTime', 'OneTime'), ('PartTime', 'PartTime'), ('FullTime', 'Fulltime')], max_length=250)),
                ('Experience', models.CharField(choices=[('Experience(0-2)years', 'Experience(0-2)years'), ('Experience(2-5)years', 'Experience(0-2)years'), ('Experience(more than 5)years', 'Experience(0-2)years')], max_length=250)),
                ('web_link', models.URLField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='OCCUPATIONS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupations', models.CharField(blank=True, max_length=700, null=True)),
                ('detailes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
